spring.application.name=RECOMMENDATION-SERVICE
spring.config.import=optional:configserver:http://localhost:8888
server.port=8090

# Logging
logging.level.com.pikuco.recommendationservice=DEBUG
logging.level.org.springframework.cloud.openfeign=DEBUG


